import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./*.html", "./js/*.js"],
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        "primary-fixed": "#e5e2e1",
        "secondary-fixed-dim": "#c6c7c5",
        "on-secondary-fixed-variant": "#454746",
        "primary-container": "#1c1b1b",
        "surface-dim": "#d3daea",
        "on-surface-variant": "#444748",
        "background": "#f9f9ff",
        "on-primary-fixed": "#1c1b1b",
        "tertiary-container": "#25005a",
        "on-primary-fixed-variant": "#474746",
        "on-tertiary-fixed": "#25005a",
        "surface-container-low": "#f0f3ff",
        "on-primary-container": "#858383",
        "primary": "#000000",
        "surface-container": "#e7eefe",
        "on-background": "#151c27",
        "outline": "#747878",
        "inverse-primary": "#c8c6c5",
        "on-tertiary-fixed-variant": "#5a00c6",
        "surface-tint": "#5f5e5e",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#1a1c1b",
        "surface-variant": "#dce2f3",
        "surface-container-highest": "#dce2f3",
        "on-tertiary-container": "#9863ff",
        "secondary-container": "#e2e3e1",
        "secondary-fixed": "#e2e3e1",
        "on-primary": "#ffffff",
        "inverse-surface": "#2a313d",
        "on-surface": "#151c27",
        "inverse-on-surface": "#ebf1ff",
        "error": "#ba1a1a",
        "surface": "#f9f9ff",
        "outline-variant": "#c4c7c7",
        "error-container": "#ffdad6",
        "on-secondary-container": "#636563",
        "primary-fixed-dim": "#c8c6c5",
        "on-secondary": "#ffffff",
        "surface-bright": "#f9f9ff",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#d2bbff",
        "surface-container-high": "#e2e8f8",
        "tertiary-fixed": "#eaddff",
        "tertiary": "#000000",
        "secondary": "#5d5f5d",
        "ai-accent": "#9863ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        unit: "4px",
        gutter: "24px",
        "margin-desktop": "40px",
        "margin-mobile": "16px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "display-lg": ["Playfair Display"],
        "label-sm": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-sm": ["Playfair Display"],
        "display-lg-mobile": ["Playfair Display"],
        "label-md": ["Inter"],
        "headline-md": ["Playfair Display"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "1", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
      },
    },
  },
  plugins: [forms, containerQueries],
};